### ISSUE TITLE
카테고리 컴포넌트 구현

### ISSUE THREAD

**Issue by jeonjeunghoon** [woowacourse-teams/2023-dong-gle#100]
### ⏰ Estimated Time

4

### 🛠️ Description

글을 담을 수 있는 카테고리와 해당 컴포넌트들을 보여주는 리스트 컴포넌트를 구현한다.

### ✅ Tasks

- [x] 카테고리 구현
- [ ] 카테고리 추가 기능 구현
- [ ] 카테고리 삭제 기능 구현
- [ ] 카테고리 수정 기능 구현
