### ISSUE TITLE
프로젝트를 위한 Actions 추가

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#122]
### ⏰ Estimated Time

1

### 🛠️ Description

PR을 날렸을때, test만 해주는 Actions를 구현하려고 한다.
Main으로 merge 됐을때 prod 서버로 배포해주는 Actions도 필요하다.
PR 만들때 Issue에서 쓴 내용 그대로 복사 붙여넣기 해주는 기능도 있으면 좋을듯하다.
전반적인 Actions 관련 코드가 들어갈듯 하다.

### ✅ Tasks

- [ ] PR 올렸을시에 작동하는 Actions 구현
- [x] Main branch로 merge시 작동하는 CICD Actions 추가
- [ ] PR Issue 복사해주는 Actions 추가
