### ISSUE TITLE
카테고리 API 구현

### ISSUE THREAD

**Issue by HubCreator** [woowacourse-teams/2023-dong-gle#129]
### ⏰ Estimated Time

3

### 🛠️ Description

카테고리에 대한 기능 개발을 한다.

### ✅ Tasks

- [x] 카테고리 추가
- [x] 카테고리 수정
- [x] 카테고리 삭제
- [x] 카테고리 목록 조회
- [x] 카테고리 내의 글 목록 조회
- [x] 카테고리 내의 글의 상세 목록 조회
