### ISSUE TITLE
테스트 코드 구현

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#137]
### ⏰ Estimated Time

2

### 🛠️ Description

시간상 넣지 못했던 테스트 코드들 구현

### ✅ Tasks

- [ ] 외부 API 서비스들 Mocking으로 호출, 응답 테스트 구현
- [ ] NotionParser 테스트 코드 구현
- [ ] 서비스 Mocking 테스트 구현
- [ ] 통합테스트 구현(외부 호출 API는 mocking)
