### ISSUE TITLE
카테고리 오류 수정 및 리팩토링

### ISSUE THREAD

**Issue by HubCreator** [woowacourse-teams/2023-dong-gle#179]
### ⏰ Estimated Time

2

### 🛠️ Description

배포 환경에서 발생하는 문제들을 해결한다.

### ✅ Tasks

- [ ] 카테고리 생성 후 목록 조회 시, 글 목록이 비어있을 때 빈 배열을 전송하도록 수정
- [ ] 글 생성시 요청 형식 수정
- [ ] 카테고리 삭제 수정
    - [ ] 삭제된 카테고리 내의 글이 비어있을 때, 기본 카테고리로 글을 이동시키는 로직을 적용하지 않도록
    - [ ] 글 삭제시 기본 카테고리가 비어있을 때 순환 참조가 일어난다.
    - [ ] 글이 있는 카테고리를 삭제시, 기본 카테고리에서 순환 참조가 일어난다.
