### ISSUE TITLE
PROD용 서버 설정 변경

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#182]
### ⏰ Estimated Time

1

### 🛠️ Description

PROD용 서버에서 달라진 서버 설정 변경

### ✅ Tasks

- [x] JPA DDL 생성 전략 변경
- [x] CICD deploy-prod.yml 수정
    - [x] DB_URL을 프로파일 별로 구분
    - [x] docker compose down 의 -v 옵션 제거
    - [x] 로그 파일 볼륨 바인딩
- [x] BE 도커 파일에 java 실행에 로컬 시간 주입
- [x] DB 로컬 타임 변경
