### ISSUE TITLE
`WritingTableView`에서 글 추가 시 해당 카테고리로 추가되도록 구현

### ISSUE THREAD

**Issue by nangkyeonglim** [woowacourse-teams/2023-dong-gle#186]
### ⏰ Estimated Time

1

### 🛠️ Description

현재 모든 글이 추가 시에 기본 카테고리로 간다.
카테고리에서 글 추가 시 해당 카테고리로 이동하도록 구현한다.

### ✅ Tasks

- [x] 카테고리에서 글 추가 시 해당 카테고리로 이동하도록 구현
- [x] 새로고침 시 404 페이지가 뜨는 웹팩 설정 수정
- [x] WritingProperty 섹션에 발행 된 블로그 없을 때 published 타이틀 없애기
