### ISSUE TITLE
Frontend CICD Docker 환경 변경

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#199]
### ⏰ Estimated Time

1

### 🛠️ Description

프론트엔드 도커 파일 prod와 dev로 나누어서 이미지 분리

### ✅ Tasks

- [ ] frontend prod, dev 이미지 분리
- [ ] github actions에서 main, develop 브랜치에 따라 이미지 빌드 분리
- [ ] docker compose에서 분리된 이미지 따로 부르도록 설정
