### ISSUE TITLE
기존 Block 엔티티 제거 후 Content를 Block으로 변경

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#246]
### ⏰ Estimated Time

1

### 🛠️ Description

현재 Block 엔티티에서 필드로 Content를 가지고 있고 양방향 관계였다. 하지만 Block 엔티티에 추가로 들어가는 정보가 없고, 데이터 테이블 구조만 복잡해진다는 피드백을 반영해 기존 Block을 없애고 Content를 Block으로 변경하는 작업을 한다.

### ✅ Tasks

- [ ] Block 엔티티 및 레파지토리 제거
- [ ] Content에 Writing 객체 필드로 추가 (ManyToOne)
- [ ] Content를 Block으로 이름 변경

### 📝 Note

Content → Block으로 이름을 변경해 직관적으로 이해할 수 있도록 변경하였습니다. 따라서 아래 엔티티 이름도 변경되었습니다.
`NormalContent` → `NormalBlock`
`CodeBlockContent` → `CodeBlock`
`ImageContent` → `ImageBlock`
