### ISSUE TITLE
로그 시스템 MDC 적용 및 CloudWatch 로그백 설정

### ISSUE THREAD

**Issue by HubCreator** [woowacourse-teams/2023-dong-gle#259]
### ⏰ Estimated Time

1

### 🛠️ Description

한 사용자가 들어와서 여러 계층에 거쳐 오류 메시지를 찍을 수 있을 것이다. 이때 기존의 로그 시스템으로는 어떤 사용자인지 추적이 불가능하다. 따라서 MDC를 적용해 UUID 및 ip정보를 로그에 추가로 남길 계획이다.

### ✅ Tasks

- [x] MDC 인터셉터 추가
- [x] logback-spring.xml 수정
- [x] AWS CloudWatch쪽으로 로그를 보내도록 설정
- [x] yml 파일 합병 및 프로파일 재구성
