### ISSUE TITLE
카테고리 기능 오류 수정

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#270]
### ⏰ Estimated Time

3

### 🛠️ Description

현재 카테고리에 다음과 같은 오류가 있다.
- 이름이 "기본"인 카테고리가 삭제되지 않는 오류 수정
- 카테고리 이름 중복 안되도록 수정
- 카테고리 이름 빈 공백으로 안되게 수정

### ✅ Tasks

- [ ] 이름이 "기본"인 카테고리가 삭제되지 않는 오류 수정
- [ ] 카테고리 이름 중복 안되도록 수정
- [ ] 카테고리 이름 빈 공백으로 안되게 수정
