### ISSUE TITLE
개발서버에 https 적용

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#366]
### ⏰ Estimated Time

1

### 🛠️ Description

현재 개발 서버에는 http 프로토콜로 ip주소를 직접 입력하는 형식으로 접근하도록 되어있다.
여기서 발생하는 문제는
1. http 프로토콜의 보안 문제들
2. 서버 ip 주소가 변경될 경우 그에 따른 환경변수들 수정
3. 노션이나 기타 OAuth 기반으로 연결된 API들이 http 프로토콜에서 작동하지 않는 경우가 있어서 OAuth 테스트를 하기 힘들다.

### ✅ Tasks

- [ ] CloudFlare의 DNS 설정에서 dev.donggle.blog 추가 및 ip 연결
- [ ] nginx에서 dev.donggle.blog로 연결하도록 설정 변경
- [ ] 개발 환경 변수들 변경
