### ISSUE TITLE
백엔드 application.properties submodule로 관리

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#370]
### ⏰ Estimated Time

1

### 🛠️ Description

현재 백엔드 환경변수들을 github action secrets로 관리중이다.
하지만 secret이 늘어날 수록 actions와 docker-compose에 추가해야하는 환경변수들이 늘어나기 때문에 submodule을 사용해 application.properties를 관리하려고 한다.

### ✅ Tasks

- [x] application.properties가 담긴 private repository를 submodule로 추가
- [x] actions에서 빌드할때 submodule을 불러오도록 변경
- [x] github actions에서 백엔드 환경 변수 제거
- [x] docker compose에서 환경 변수 제거
