### ISSUE TITLE
글과 카테고리 EAGER 로딩 개선

### ISSUE THREAD

**Issue by ezzanzzan** [woowacourse-teams/2023-dong-gle#374]
### ⏰ Estimated Time

3

### 🛠️ Description

현재 프로젝트에서 Writing, Category Entity는 각각 자기 자신과 @OneToOne 연관 관계를 가지고 이는 Eager Loading(즉시 로딩)으로 관리되고 있다.
해당 로직을 Lazy Loading(지연 로딩)으로 바꿔 성능 개선을 해보고자 한다.

### ✅ Tasks

- [ ] Category의 nextCategory 지연 로딩으로 변경
- [ ] Wriitng의 nextWiritng 지연 로딩으로 변경
- [ ] 연관관계로 엮여 있는 필드에 대한 toString 변경
