### ISSUE TITLE
요청 크기 줄이기

### ISSUE THREAD

**Issue by jeonjeunghoon** [woowacourse-teams/2023-dong-gle#389]
### ⏰ Estimated Time

3

### 🛠️ Description

<img width="323" alt="스크린샷 2023-09-11 오후 3 09 18" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/e65392d4-a434-453e-8eb6-53ce74c38d8b">

로딩 최적화를 위해 번들 파일의 크기를 줄인다.

### ✅ Tasks

- [x] 소스코드 파일 크기 줄이기
- [x] 이미지 크기 줄이기
- [x] 코드 스플리팅 적용하기
- [x] 폰트, Introduce 페이지의 icon에 preload 적용
- [x] highlightJS에 defer 추가
