### ISSUE TITLE
글 정보 조회 API에 발행한 글 url 추가

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#406]
### ⏰ Estimated Time

1

### 🛠️ Description

글을 발행한 뒤 발행한 글의 url을 글 정보 조회 API에 추가해 사용자가 글을 발행한 뒤 쉽게 발행한 글을 볼 수 있도록 url을 추가한다.

### ✅ Tasks

- [ ]  발행한 뒤 글의 url을 API로부터 받아온다.
- [ ] 받아온 url을 BlogWriting 엔티티에 저장
- [ ] 글 정보 조회 API 응답에 url 추가
