### ISSUE TITLE
동시에 글 또는 카테고리 추가시 마지막 글,마지막 카테고리가 여러개 추가되는 문제

### ISSUE THREAD

**Issue by ingpyo** [woowacourse-teams/2023-dong-gle#414]
### ⏰ Estimated Time

2

### 🛠️ Description

글,카테고리의 순서를 나타내주기 위해 하나의 객체가 그다음 객체의 아이디를 들고있다.
하지만 동시에 요청이왔을때 그 다음 객체를(또는 마지막)바라보고 있는 객체가 여려개 생겨 에러가나는 문제

### ✅ Tasks

- [ ] Writing 테이블에 categoryId와 nextId를 한번에 복합 유니크 인덱스 생성
- [ ] Category 테이블에 memberId와 nextId를 한번에 복합 유니크 인덱스 생성
- [ ] 자기 참조하고 있는 Writing의 필드를 next Writing의 Id를 갖고있도록 로직 수정
- [ ] 자기 참조하고 있는 Category의 필드를 next Category의 Id를 갖고있도록 로직 수정
