### ISSUE TITLE
프론트엔드 개발환경 추가 설정

### ISSUE THREAD

**Issue by nangkyeonglim** [woowacourse-teams/2023-dong-gle#44]
### ⏰ Estimated Time

1

### 🛠️ Description

프론트엔드 개발환경 추가 설정을 진행한다.

### ✅ Tasks

- [x] svg 이용가능 하도록 웹팩 설정
- [x] index.d.ts에 svg 정의
- [x] 스토리북에서 svg 이용가능 하도록 main.ts 설정
- [x] tsconfig, eslint 충돌 에러 해결
- [x] 개발 리소스(asset) 추가
- [x] 스토리북 autodocs 설정
- [x] 스토리북 용 컴포넌트 추가
