### ISSUE TITLE
Prod CICD 로직 변경

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#579]
### ⏰ Estimated Time

1

### 🛠️ Description

현재 Prod CICD의 경우 메인 머지가 될 경우 발생되는데, fe, be가 동시에 작동하기 때문에 deploy가 두 번 동시에 일어나게 된다. 따라서 두 작업을 순차적으로 진행하여 deploy가 한 번만 일어나도록 변경한다.

### ✅ Tasks

- [ ] deploy-prod.yml에서 build 작업을 수행하도록 변경
- [ ] build-prod.yml은 main 머지에서는 발동하지 않도록 변경
- [ ] 무중단 배포 스크립트 사용
