### ISSUE TITLE
반응형 스타일 적용하기

### ISSUE THREAD

**Issue by jeonjeunghoon** [woowacourse-teams/2023-dong-gle#592]
### ⏰ Estimated Time

3

### 🛠️ Description

현재 모바일 환경에서 화면이 제대로 나오지 않는다.

### ✅ Tasks

- [x] 소개 페이지 반응형
- [ ] 스페이스 페이지 반응형
- [x] 마이 페이지 반응형
- [ ] 글 테이블 페이지 반응형
- [ ] 글 뷰 페이지 반응형
- [x] 모달 반응형
- [ ] 글 테이블 반응형
