### ISSUE TITLE
동글 CI/CD 구축

### ISSUE THREAD

**Issue by echo724** [woowacourse-teams/2023-dong-gle#62]
### ⏰ Estimated Time

3

### 🛠️ Description

백엔드/프론트엔드 서버의 CI/CD를 구축한다.

### ✅ Tasks

- [x] github dev workflow 작성
- [x] github prod workflow 작성
- [x] docker-compose 파일 작성
