### ISSUE TITLE
아코디언 컴포넌트 구현

### ISSUE THREAD

**Issue by jeonjeunghoon** [woowacourse-teams/2023-dong-gle#99]
### ⏰ Estimated Time

2

### 🛠️ Description

카테고리를 위한 컴포넌트 구현

### ✅ Tasks

- [x] 아코디언 컴포넌트 구현
  - [x] 외부에서 [제목, 내용] 튜플 배열을 받는 방법으로 수정
  - [x] 글 목록이 비어있을 때 처리
  - [x] HeaderButton 컴포넌트 내 header를 감싸는 p태그 삭제
  ```tsx
    return (
      <S.Button {...rest}>
      ...
          <p>{header}</p>
      ...
      </S.Button>
    );
  ```
- [x] 아코디언 스토리북 작성
